function output = bruteForce(message)
  alpha = 1; #untuk key pertama dimulai dari 1
  beta = 0; #untuk key kedua dimulai dari 0
  
  for x=0:25 #looping dari 0 : 25
    
    if mod(x,2) == 0#Supaya ambil hanya bilangan ganjil, karena untuk mencari A' harus ganjil
      continue
    endif
    
    alpha = x;# memasukan value ke key1 atau alpha
  
    for y=0:25 #looping dari 0 : 25
      
      beta = y;# memasukan value ke key2 atau beta
      disp(['Alpha: ', num2str(x), ' Beta: ', num2str(y)])
      affine_decrypt(message,alpha,beta);#proses decryption
      
    endfor
  endfor
endfunction
#NUXWU ZUVUO FUHECU OSHZAFAHE TSHEEKHUUH QHLAFOUYQ ESAYTUYQUV EKHU TSVUCYUHUUH TSONUHEKHUH HUYQAHUV ZUH KHRKC OSHZKCKHE RSFWKJKZHIU UESHZU TFQAFQRUY HUWUGQRU, ZQTSFVKCUH CSNQJUCUH YURK TSRU IUHE OSHEUGK TUZU YURK FSLSFSHYQ ESAYTUYQUV, YURK YRUHZUF, YURK NUYQY ZURU, ZUH YURK ESATAFRUV; NUXWU NSFZUYUFCUH TSFRQONUHEUH YSNUEUQOUHU ZQOUCYKZ TUZU RSFYSNKR, TSFVK OSHSRUTCUH TSFURKFUH TFSYQZSH RSHRUHE TSFGSTURUH TSVUCYUHUUH CSNQJUCUH YURK TSRU TUZU RQHECUR CSRSVQRQUH TSRU YCUVU RSFRSHRK. CSNQJUCUH YURK TSRU, IUHE YSVUHJKRHIU ZQYSNKR CYT UZUVUX UFUXUH YRFURSEQY ZUVUO RSFTSHKXQHIU YURK TSRU IUHE OSHEUGK TUZU YURK FSLSFSHYQ ESAYTUYQUV, YURK YRUHZUF, YURK NUYQY ZURU, ZUH YURK ESATAFRUV TUZU RQHECUR CSRSVQRQUH TSRU YCUVU ZQOUCYKZ. TSRU UZUVUX YKURK EUONUFUH ZUFQ KHYKF-KHYKF UVUO URUK NKURUH OUHKYQU, IUHE NSFUZU ZQ URUY OUKTKH ZQ NUWUX TSFOKCUUH NKOQ IUHE ZQEUONUFCUH TUZU YKURK NQZUHE ZURUF ZSHEUH YCUVU RSFRSHRK. ESAYTUYQUV URUK FKUHE CSNKOQUH UZUVUX UYTSC CSFKUHEUH IUHE OSHKHJKCCUH VACUYQ, VSRUC, ZUH TAYQYQ.